### ISSUE TITLE
Any chance of an update?

### ISSUE THREAD

**Issue by i-am-the-slime** [purescript-react/purescript-react-icons#4]
I'm pretty keen on the Heroicons v2 icons 😁

**Comment by andys8** [comment]
Hey, of course. Could you give [`1.1.0`](https://pursuit.purescript.org/packages/purescript-react-icons/1.1.0) a try? 

It looks like Heroicons 1 and Heroicons 2 use the same names, but look differently. 

![image](https://user-images.githubusercontent.com/13085980/219410378-e202be9c-40ff-4a55-b4b0-1894b20e94fe.png)

**Comment by andys8** [comment]
Updated tested and confirmed by @i-am-the-slime :heavy_check_mark:
