### ISSUE TITLE
Update to 4.9.0

### ISSUE THREAD

**Issue by i-am-the-slime** [purescript-react/purescript-react-icons#6]
Do you think we could have a github action that updates this whole package?

**Comment by andys8** [comment]
Major releases seem to rename or add icon libraries (e.g. 4.9.0). Not sure if it's saving work to automate this and doing the whole PureScript release business (which is also about to change with the new registry - or did it already?).

Probably easier to update once in a while or would you want to bake this into CI?

**Comment by andys8** [comment]
Removal of `all.d.ts` is a breaking change (https://github.com/react-icons/react-icons/releases/tag/v4.9.0)

**Comment by andys8** [comment]
Should be done. Let me know if you encounter any issues.
